package net.georgezeng.misterx.gwt.ui.map;

import java.util.ArrayList;
import java.util.List;

import net.georgezeng.misterx.gwt.vo.RoadInfoVO;
import net.georgezeng.misterx.gwt.vo.StationRoadInfoVO;
import net.georgezeng.misterx.gwt.vo.StationVO;
import net.georgezeng.misterx.shared.enums.RoadSide;
import net.georgezeng.misterx.shared.enums.RoadType;

public final class RoadInfos {

	public static final RoadInfoVO LEFT_TAXI = new RoadInfoVO(RoadType.Taxi, RoadSide.Left);
	public static final RoadInfoVO MIDDLE_TAXI = new RoadInfoVO(RoadType.Taxi, RoadSide.Middle);
	public static final RoadInfoVO RIGHT_TAXI = new RoadInfoVO(RoadType.Taxi, RoadSide.Right);

	public static final RoadInfoVO LEFT_BUS = new RoadInfoVO(RoadType.Bus, RoadSide.Left);
	public static final RoadInfoVO MIDDLE_BUS = new RoadInfoVO(RoadType.Bus, RoadSide.Middle);
	public static final RoadInfoVO RIGHT_BUS = new RoadInfoVO(RoadType.Bus, RoadSide.Right);

	public static final RoadInfoVO LEFT_METRO = new RoadInfoVO(RoadType.Metro, RoadSide.Left);
	public static final RoadInfoVO MIDDLE_METRO = new RoadInfoVO(RoadType.Metro, RoadSide.Middle);
	public static final RoadInfoVO RIGHT_METRO = new RoadInfoVO(RoadType.Metro, RoadSide.Right);

	public static final List<StationRoadInfoVO> LIST = new ArrayList<StationRoadInfoVO>();

	private static final StationRoadInfoVO newVO(StationVO start, StationVO end, RoadInfoVO... types) {
		StationRoadInfoVO vo = new StationRoadInfoVO(start, end, types);
		LIST.add(vo);
		return vo;
	}

	public static final StationRoadInfoVO R1_8 = newVO(Stations.S1, Stations.S8, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R1_9 = newVO(Stations.S1, Stations.S9, LEFT_TAXI, MIDDLE_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R2_10 = newVO(Stations.S2, Stations.S10, MIDDLE_TAXI);
	public static final StationRoadInfoVO R2_20 = newVO(Stations.S2, Stations.S20, MIDDLE_TAXI);
	public static final StationRoadInfoVO R3_4 = newVO(Stations.S3, Stations.S4, MIDDLE_TAXI);
	public static final StationRoadInfoVO R3_11 = newVO(Stations.S3, Stations.S11, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R3_12 = newVO(Stations.S3, Stations.S12, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R4_13 = newVO(Stations.S4, Stations.S13, MIDDLE_TAXI);
	public static final StationRoadInfoVO R5_15 = newVO(Stations.S5, Stations.S15, MIDDLE_TAXI);
	public static final StationRoadInfoVO R5_16 = newVO(Stations.S5, Stations.S16, MIDDLE_TAXI);
	public static final StationRoadInfoVO R6_7 = newVO(Stations.S6, Stations.S7, MIDDLE_TAXI);
	public static final StationRoadInfoVO R6_29 = newVO(Stations.S6, Stations.S29, MIDDLE_TAXI);
	public static final StationRoadInfoVO R7_17 = newVO(Stations.S7, Stations.S17, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R8_18 = newVO(Stations.S8, Stations.S18, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R8_19 = newVO(Stations.S8, Stations.S19, MIDDLE_TAXI);
	public static final StationRoadInfoVO R9_19 = newVO(Stations.S9, Stations.S19, MIDDLE_TAXI);
	public static final StationRoadInfoVO R9_20 = newVO(Stations.S9, Stations.S20, LEFT_TAXI);
	public static final StationRoadInfoVO R9_46 = newVO(Stations.S9, Stations.S46, MIDDLE_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R10_11 = newVO(Stations.S10, Stations.S11, MIDDLE_TAXI);
	public static final StationRoadInfoVO R10_21 = newVO(Stations.S10, Stations.S21, MIDDLE_TAXI);
	public static final StationRoadInfoVO R10_34 = newVO(Stations.S10, Stations.S34, MIDDLE_TAXI);
	
	public static final StationRoadInfoVO R11_22 = newVO(Stations.S11, Stations.S22, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R12_23 = newVO(Stations.S12, Stations.S23, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R13_14 = newVO(Stations.S13, Stations.S14, LEFT_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R13_23 = newVO(Stations.S13, Stations.S23, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R13_24 = newVO(Stations.S13, Stations.S24, MIDDLE_TAXI);
	public static final StationRoadInfoVO R13_25 = newVO(Stations.S13, Stations.S25, MIDDLE_BUS);
	public static final StationRoadInfoVO R13_50 = newVO(Stations.S13, Stations.S50, RIGHT_METRO);
	public static final StationRoadInfoVO R14_15 = newVO(Stations.S14, Stations.S15, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R14_25 = newVO(Stations.S14, Stations.S25, MIDDLE_TAXI);
	public static final StationRoadInfoVO R15_16 = newVO(Stations.S15, Stations.S16, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R15_26 = newVO(Stations.S15, Stations.S26, MIDDLE_TAXI);
	public static final StationRoadInfoVO R15_28 = newVO(Stations.S15, Stations.S28, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R16_28 = newVO(Stations.S16, Stations.S28, MIDDLE_TAXI);
	public static final StationRoadInfoVO R16_29 = newVO(Stations.S16, Stations.S29, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R17_29 = newVO(Stations.S17, Stations.S29, MIDDLE_TAXI);
	public static final StationRoadInfoVO R17_30 = newVO(Stations.S17, Stations.S30, MIDDLE_TAXI);
	public static final StationRoadInfoVO R17_42 = newVO(Stations.S17, Stations.S42, MIDDLE_BUS);
	public static final StationRoadInfoVO R18_31 = newVO(Stations.S18, Stations.S31, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R18_43 = newVO(Stations.S18, Stations.S43, MIDDLE_TAXI);
	public static final StationRoadInfoVO R19_32 = newVO(Stations.S19, Stations.S32, MIDDLE_TAXI);
	public static final StationRoadInfoVO R20_33 = newVO(Stations.S20, Stations.S33, LEFT_TAXI);
	
	public static final StationRoadInfoVO R21_33 = newVO(Stations.S21, Stations.S33, MIDDLE_TAXI);
	public static final StationRoadInfoVO R22_23 = newVO(Stations.S22, Stations.S23, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R22_34 = newVO(Stations.S22, Stations.S34, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R22_35 = newVO(Stations.S22, Stations.S35, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R23_37 = newVO(Stations.S23, Stations.S37, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R24_37 = newVO(Stations.S24, Stations.S37, MIDDLE_TAXI);
	public static final StationRoadInfoVO R24_38 = newVO(Stations.S24, Stations.S38, MIDDLE_TAXI);
	public static final StationRoadInfoVO R25_38 = newVO(Stations.S25, Stations.S38, MIDDLE_TAXI);
	public static final StationRoadInfoVO R25_39 = newVO(Stations.S25, Stations.S39, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R26_27 = newVO(Stations.S26, Stations.S27, MIDDLE_TAXI);
	public static final StationRoadInfoVO R26_39 = newVO(Stations.S26, Stations.S39, MIDDLE_TAXI);
	public static final StationRoadInfoVO R27_28 = newVO(Stations.S27, Stations.S28, MIDDLE_TAXI);
	public static final StationRoadInfoVO R27_40 = newVO(Stations.S27, Stations.S40, MIDDLE_TAXI);
	public static final StationRoadInfoVO R28_41 = newVO(Stations.S28, Stations.S41, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R29_41 = newVO(Stations.S29, Stations.S41, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R29_42 = newVO(Stations.S29, Stations.S42, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R29_55 = newVO(Stations.S29, Stations.S55, LEFT_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R30_42 = newVO(Stations.S30, Stations.S42, MIDDLE_TAXI);
	public static final StationRoadInfoVO R31_43 = newVO(Stations.S31, Stations.S43, MIDDLE_TAXI);
	public static final StationRoadInfoVO R31_44 = newVO(Stations.S31, Stations.S44, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R32_33 = newVO(Stations.S32, Stations.S33, MIDDLE_TAXI);
	public static final StationRoadInfoVO R32_44 = newVO(Stations.S32, Stations.S44, MIDDLE_TAXI);
	public static final StationRoadInfoVO R32_45 = newVO(Stations.S32, Stations.S45, MIDDLE_TAXI);
	public static final StationRoadInfoVO R33_46 = newVO(Stations.S33, Stations.S46, LEFT_TAXI);
	public static final StationRoadInfoVO R34_47 = newVO(Stations.S34, Stations.S47, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R34_48 = newVO(Stations.S34, Stations.S48, LEFT_TAXI);
	public static final StationRoadInfoVO R34_63 = newVO(Stations.S34, Stations.S63, RIGHT_BUS);
	public static final StationRoadInfoVO R35_36 = newVO(Stations.S35, Stations.S36, MIDDLE_TAXI);
	public static final StationRoadInfoVO R35_48 = newVO(Stations.S35, Stations.S48, MIDDLE_TAXI);
	public static final StationRoadInfoVO R35_65 = newVO(Stations.S35, Stations.S65, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R36_37 = newVO(Stations.S36, Stations.S37, MIDDLE_TAXI);
	public static final StationRoadInfoVO R36_49 = newVO(Stations.S36, Stations.S49, MIDDLE_TAXI);
	public static final StationRoadInfoVO R37_50 = newVO(Stations.S37, Stations.S50, LEFT_TAXI, MIDDLE_BUS);
	public static final StationRoadInfoVO R38_50 = newVO(Stations.S38, Stations.S50, MIDDLE_TAXI);
	public static final StationRoadInfoVO R38_51 = newVO(Stations.S38, Stations.S51, MIDDLE_TAXI);
	public static final StationRoadInfoVO R39_51 = newVO(Stations.S39, Stations.S51, MIDDLE_TAXI);
	public static final StationRoadInfoVO R39_52 = newVO(Stations.S39, Stations.S52, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R40_41 = newVO(Stations.S40, Stations.S41, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R40_52 = newVO(Stations.S40, Stations.S52, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R40_53 = newVO(Stations.S40, Stations.S53, MIDDLE_TAXI);
	
	public static final StationRoadInfoVO R41_54 = newVO(Stations.S41, Stations.S54, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R42_56 = newVO(Stations.S42, Stations.S56, MIDDLE_TAXI);
	public static final StationRoadInfoVO R42_72 = newVO(Stations.S42, Stations.S72, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R43_57 = newVO(Stations.S43, Stations.S57, MIDDLE_TAXI);
	public static final StationRoadInfoVO R44_58 = newVO(Stations.S44, Stations.S58, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R45_46 = newVO(Stations.S45, Stations.S46, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R45_58 = newVO(Stations.S45, Stations.S58, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R45_59 = newVO(Stations.S45, Stations.S59, MIDDLE_TAXI);
	public static final StationRoadInfoVO R45_60 = newVO(Stations.S45, Stations.S60, MIDDLE_TAXI);
	public static final StationRoadInfoVO R46_47 = newVO(Stations.S46, Stations.S47, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R46_61 = newVO(Stations.S46, Stations.S61, LEFT_TAXI, MIDDLE_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R47_62 = newVO(Stations.S47, Stations.S62, MIDDLE_TAXI);
	public static final StationRoadInfoVO R48_62 = newVO(Stations.S48, Stations.S62, MIDDLE_TAXI);
	public static final StationRoadInfoVO R48_63 = newVO(Stations.S48, Stations.S63, MIDDLE_TAXI);
	public static final StationRoadInfoVO R49_50 = newVO(Stations.S49, Stations.S50, MIDDLE_TAXI);
	public static final StationRoadInfoVO R49_66 = newVO(Stations.S49, Stations.S66, MIDDLE_TAXI);
	public static final StationRoadInfoVO R50_67 = newVO(Stations.S50, Stations.S67, MIDDLE_METRO, RIGHT_BUS);

	public static final StationRoadInfoVO R51_52 = newVO(Stations.S51, Stations.S52, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R51_67 = newVO(Stations.S51, Stations.S67, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R51_68 = newVO(Stations.S51, Stations.S68, MIDDLE_TAXI);
	public static final StationRoadInfoVO R52_69 = newVO(Stations.S52, Stations.S69, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R53_54 = newVO(Stations.S53, Stations.S54, MIDDLE_TAXI);
	public static final StationRoadInfoVO R53_69 = newVO(Stations.S53, Stations.S69, MIDDLE_TAXI);
	public static final StationRoadInfoVO R54_55 = newVO(Stations.S54, Stations.S55, MIDDLE_TAXI);
	public static final StationRoadInfoVO R54_70 = newVO(Stations.S54, Stations.S70, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R55_71 = newVO(Stations.S55, Stations.S71, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	
	public static final StationRoadInfoVO R56_91 = newVO(Stations.S56, Stations.S91, MIDDLE_TAXI);
	public static final StationRoadInfoVO R57_58 = newVO(Stations.S57, Stations.S58, MIDDLE_TAXI);
	public static final StationRoadInfoVO R57_73 = newVO(Stations.S57, Stations.S73, MIDDLE_TAXI);
	public static final StationRoadInfoVO R58_59 = newVO(Stations.S58, Stations.S59, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R58_74 = newVO(Stations.S58, Stations.S74, LEFT_TAXI, MIDDLE_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R58_75 = newVO(Stations.S58, Stations.S75, MIDDLE_TAXI);
	public static final StationRoadInfoVO R59_75 = newVO(Stations.S59, Stations.S75, MIDDLE_TAXI);
	public static final StationRoadInfoVO R59_76 = newVO(Stations.S59, Stations.S76, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R60_61 = newVO(Stations.S60, Stations.S61, MIDDLE_TAXI);
	public static final StationRoadInfoVO R60_76 = newVO(Stations.S60, Stations.S76, MIDDLE_TAXI);
	
	public static final StationRoadInfoVO R61_62 = newVO(Stations.S61, Stations.S62, LEFT_METRO, RIGHT_TAXI);
	public static final StationRoadInfoVO R61_76 = newVO(Stations.S61, Stations.S76, MIDDLE_TAXI);
	public static final StationRoadInfoVO R61_78 = newVO(Stations.S61, Stations.S78, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R62_79 = newVO(Stations.S62, Stations.S79, LEFT_METRO, MIDDLE_TAXI);
	public static final StationRoadInfoVO R63_64 = newVO(Stations.S63, Stations.S64, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R63_79 = newVO(Stations.S63, Stations.S79, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R63_80 = newVO(Stations.S63, Stations.S80, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R64_65 = newVO(Stations.S64, Stations.S65, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R64_81 = newVO(Stations.S64, Stations.S81, MIDDLE_TAXI);
	public static final StationRoadInfoVO R65_66 = newVO(Stations.S65, Stations.S66, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R65_82 = newVO(Stations.S65, Stations.S82, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R66_67 = newVO(Stations.S66, Stations.S67, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R66_82 = newVO(Stations.S66, Stations.S82, MIDDLE_TAXI);
	public static final StationRoadInfoVO R67_68 = newVO(Stations.S67, Stations.S68, LEFT_METRO, RIGHT_TAXI);
	public static final StationRoadInfoVO R67_83 = newVO(Stations.S67, Stations.S83, MIDDLE_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R67_84 = newVO(Stations.S67, Stations.S84, MIDDLE_TAXI);
	public static final StationRoadInfoVO R67_102 = newVO(Stations.S67, Stations.S102, MIDDLE_BUS);
	public static final StationRoadInfoVO R68_69 = newVO(Stations.S68, Stations.S69, LEFT_TAXI);
	public static final StationRoadInfoVO R68_85 = newVO(Stations.S68, Stations.S85, MIDDLE_TAXI);
	public static final StationRoadInfoVO R68_89 = newVO(Stations.S68, Stations.S89, MIDDLE_METRO);
	public static final StationRoadInfoVO R69_86 = newVO(Stations.S69, Stations.S86, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R70_71 = newVO(Stations.S70, Stations.S71, MIDDLE_TAXI);
	public static final StationRoadInfoVO R70_87 = newVO(Stations.S70, Stations.S87, LEFT_TAXI, RIGHT_BUS);
	
	public static final StationRoadInfoVO R71_72 = newVO(Stations.S71, Stations.S72, MIDDLE_TAXI);
	public static final StationRoadInfoVO R71_89 = newVO(Stations.S71, Stations.S89, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R72_90 = newVO(Stations.S72, Stations.S90, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R72_91 = newVO(Stations.S72, Stations.S91, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R73_74 = newVO(Stations.S73, Stations.S74, MIDDLE_TAXI);
	public static final StationRoadInfoVO R73_92 = newVO(Stations.S73, Stations.S92, MIDDLE_TAXI);
	public static final StationRoadInfoVO R74_75 = newVO(Stations.S74, Stations.S75, RIGHT_TAXI);
	public static final StationRoadInfoVO R74_92 = newVO(Stations.S74, Stations.S92, MIDDLE_TAXI);
	public static final StationRoadInfoVO R74_94 = newVO(Stations.S74, Stations.S94, MIDDLE_BUS);
	public static final StationRoadInfoVO R75_94 = newVO(Stations.S75, Stations.S94, MIDDLE_TAXI);
	public static final StationRoadInfoVO R76_77 = newVO(Stations.S76, Stations.S77, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R77_78 = newVO(Stations.S77, Stations.S78, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R77_95 = newVO(Stations.S77, Stations.S95, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R77_96 = newVO(Stations.S77, Stations.S96, LEFT_TAXI);
	public static final StationRoadInfoVO R77_124 = newVO(Stations.S77, Stations.S124, MIDDLE_BUS);
	public static final StationRoadInfoVO R78_79 = newVO(Stations.S78, Stations.S79, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R78_97 = newVO(Stations.S78, Stations.S97, MIDDLE_TAXI);
	public static final StationRoadInfoVO R79_98 = newVO(Stations.S79, Stations.S98, LEFT_METRO, RIGHT_TAXI);
	public static final StationRoadInfoVO R80_99 = newVO(Stations.S80, Stations.S99, MIDDLE_TAXI);
	public static final StationRoadInfoVO R80_100 = newVO(Stations.S80, Stations.S100, LEFT_TAXI, RIGHT_BUS);
	

	public static final StationRoadInfoVO R81_82 = newVO(Stations.S81, Stations.S82, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R81_100 = newVO(Stations.S81, Stations.S100, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R82_101 = newVO(Stations.S82, Stations.S101, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R82_83 = newVO(Stations.S82, Stations.S83, MIDDLE_BUS);
	public static final StationRoadInfoVO R83_101 = newVO(Stations.S83, Stations.S101, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R83_102 = newVO(Stations.S83, Stations.S102, MIDDLE_TAXI);
	public static final StationRoadInfoVO R84_85 = newVO(Stations.S84, Stations.S85, MIDDLE_TAXI);
	public static final StationRoadInfoVO R85_103 = newVO(Stations.S85, Stations.S103, MIDDLE_TAXI);
	public static final StationRoadInfoVO R86_87 = newVO(Stations.S86, Stations.S87, MIDDLE_BUS);
	public static final StationRoadInfoVO R86_103 = newVO(Stations.S86, Stations.S103, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R86_104 = newVO(Stations.S86, Stations.S104, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R87_88 = newVO(Stations.S87, Stations.S88, LEFT_TAXI, MIDDLE_BUS);
	public static final StationRoadInfoVO R88_89 = newVO(Stations.S88, Stations.S89, LEFT_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R88_104 = newVO(Stations.S88, Stations.S104, MIDDLE_METRO);
	public static final StationRoadInfoVO R88_105 = newVO(Stations.S88, Stations.S105, MIDDLE_BUS);
	public static final StationRoadInfoVO R88_117 = newVO(Stations.S88, Stations.S117, MIDDLE_TAXI);
	public static final StationRoadInfoVO R89_105 = newVO(Stations.S89, Stations.S105, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R90_91 = newVO(Stations.S90, Stations.S91, LEFT_TAXI);
	public static final StationRoadInfoVO R90_105 = newVO(Stations.S90, Stations.S105, LEFT_TAXI, RIGHT_BUS);
	
	public static final StationRoadInfoVO R91_107 = newVO(Stations.S91, Stations.S107, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R92_93 = newVO(Stations.S92, Stations.S93, MIDDLE_TAXI);
	public static final StationRoadInfoVO R93_94 = newVO(Stations.S93, Stations.S94, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R94_95 = newVO(Stations.S94, Stations.S95, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R95_122 = newVO(Stations.S95, Stations.S122, MIDDLE_TAXI);
	public static final StationRoadInfoVO R96_97 = newVO(Stations.S96, Stations.S97, MIDDLE_TAXI);
	public static final StationRoadInfoVO R96_109 = newVO(Stations.S96, Stations.S109, MIDDLE_TAXI);
	public static final StationRoadInfoVO R97_98 = newVO(Stations.S97, Stations.S98, MIDDLE_TAXI);
	public static final StationRoadInfoVO R97_109 = newVO(Stations.S97, Stations.S109, MIDDLE_TAXI);
	public static final StationRoadInfoVO R98_99 = newVO(Stations.S98, Stations.S99, MIDDLE_TAXI);
	public static final StationRoadInfoVO R98_110 = newVO(Stations.S98, Stations.S110, LEFT_METRO, RIGHT_TAXI);
	public static final StationRoadInfoVO R99_110 = newVO(Stations.S99, Stations.S110, MIDDLE_TAXI);
	public static final StationRoadInfoVO R99_112 = newVO(Stations.S99, Stations.S112, MIDDLE_TAXI);
	public static final StationRoadInfoVO R100_101 = newVO(Stations.S100, Stations.S101, MIDDLE_METRO, RIGHT_TAXI);
	public static final StationRoadInfoVO R100_112 = newVO(Stations.S100, Stations.S112, LEFT_TAXI, MIDDLE_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R100_113 = newVO(Stations.S100, Stations.S113, MIDDLE_TAXI);
	
	public static final StationRoadInfoVO R101_114 = newVO(Stations.S101, Stations.S114, MIDDLE_BUS);
	public static final StationRoadInfoVO R102_103 = newVO(Stations.S102, Stations.S103, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R102_115 = newVO(Stations.S102, Stations.S115, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R104_115 = newVO(Stations.S104, Stations.S115, MIDDLE_METRO);
	public static final StationRoadInfoVO R104_116 = newVO(Stations.S104, Stations.S116, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R105_106 = newVO(Stations.S105, Stations.S106, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R105_108 = newVO(Stations.S105, Stations.S108, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R106_107 = newVO(Stations.S106, Stations.S107, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R107_119 = newVO(Stations.S107, Stations.S119, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R108_117 = newVO(Stations.S108, Stations.S117, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R108_119 = newVO(Stations.S108, Stations.S119, MIDDLE_TAXI);
	public static final StationRoadInfoVO R108_135 = newVO(Stations.S108, Stations.S135, LEFT_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R109_110 = newVO(Stations.S109, Stations.S110, MIDDLE_TAXI);
	public static final StationRoadInfoVO R109_124 = newVO(Stations.S109, Stations.S124, MIDDLE_TAXI);
	public static final StationRoadInfoVO R110_111 = newVO(Stations.S110, Stations.S111, LEFT_TAXI, MIDDLE_METRO);
	
	public static final StationRoadInfoVO R111_112 = newVO(Stations.S111, Stations.S112, LEFT_BUS, MIDDLE_METRO, LEFT_TAXI);
	public static final StationRoadInfoVO R111_124 = newVO(Stations.S111, Stations.S124, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R111_130 = newVO(Stations.S111, Stations.S130, MIDDLE_METRO);
	public static final StationRoadInfoVO R112_125 = newVO(Stations.S112, Stations.S125, MIDDLE_TAXI);
	public static final StationRoadInfoVO R113_114 = newVO(Stations.S113, Stations.S114, MIDDLE_TAXI);
	public static final StationRoadInfoVO R113_125 = newVO(Stations.S113, Stations.S125, MIDDLE_TAXI);
	public static final StationRoadInfoVO R114_115 = newVO(Stations.S114, Stations.S115, MIDDLE_TAXI);
	public static final StationRoadInfoVO R114_126 = newVO(Stations.S114, Stations.S126, MIDDLE_TAXI);
	public static final StationRoadInfoVO R114_131 = newVO(Stations.S114, Stations.S131, MIDDLE_TAXI);
	public static final StationRoadInfoVO R114_132 = newVO(Stations.S114, Stations.S132, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R115_126 = newVO(Stations.S115, Stations.S126, LEFT_METRO, RIGHT_TAXI);
	public static final StationRoadInfoVO R115_127 = newVO(Stations.S115, Stations.S127, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R116_117 = newVO(Stations.S116, Stations.S117, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R116_118 = newVO(Stations.S116, Stations.S118, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R116_127 = newVO(Stations.S116, Stations.S127, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R117_129 = newVO(Stations.S117, Stations.S129, MIDDLE_TAXI);
	public static final StationRoadInfoVO R118_129 = newVO(Stations.S118, Stations.S129, MIDDLE_TAXI);
	public static final StationRoadInfoVO R118_134 = newVO(Stations.S118, Stations.S134, MIDDLE_TAXI);
	public static final StationRoadInfoVO R118_142 = newVO(Stations.S118, Stations.S142, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R119_136 = newVO(Stations.S119, Stations.S136, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R120_121 = newVO(Stations.S120, Stations.S121, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R120_144 = newVO(Stations.S120, Stations.S144, LEFT_BUS, RIGHT_TAXI);
	
	public static final StationRoadInfoVO R121_122 = newVO(Stations.S121, Stations.S122, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R121_145 = newVO(Stations.S121, Stations.S145, MIDDLE_TAXI);
	public static final StationRoadInfoVO R122_123 = newVO(Stations.S122, Stations.S123, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R122_146 = newVO(Stations.S122, Stations.S146, MIDDLE_TAXI);
	public static final StationRoadInfoVO R123_124 = newVO(Stations.S123, Stations.S124, LEFT_TAXI, MIDDLE_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R123_137 = newVO(Stations.S123, Stations.S137, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R123_148 = newVO(Stations.S123, Stations.S148, MIDDLE_TAXI);
	public static final StationRoadInfoVO R123_149 = newVO(Stations.S123, Stations.S149, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R124_130 = newVO(Stations.S124, Stations.S130, MIDDLE_TAXI);
	public static final StationRoadInfoVO R124_138 = newVO(Stations.S124, Stations.S138, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R125_131 = newVO(Stations.S125, Stations.S131, MIDDLE_TAXI);
	public static final StationRoadInfoVO R126_127 = newVO(Stations.S126, Stations.S127, MIDDLE_TAXI);
	public static final StationRoadInfoVO R126_140 = newVO(Stations.S126, Stations.S140, MIDDLE_TAXI);
	public static final StationRoadInfoVO R127_133 = newVO(Stations.S127, Stations.S133, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R127_134 = newVO(Stations.S127, Stations.S134, MIDDLE_TAXI);
	public static final StationRoadInfoVO R128_142 = newVO(Stations.S128, Stations.S142, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R128_143 = newVO(Stations.S128, Stations.S143, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R128_160 = newVO(Stations.S128, Stations.S160, MIDDLE_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R128_172 = newVO(Stations.S128, Stations.S172, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R128_188 = newVO(Stations.S128, Stations.S188, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R129_135 = newVO(Stations.S129, Stations.S135, MIDDLE_TAXI);
	public static final StationRoadInfoVO R129_142 = newVO(Stations.S129, Stations.S142, MIDDLE_TAXI);
	public static final StationRoadInfoVO R129_143 = newVO(Stations.S129, Stations.S143, MIDDLE_TAXI);
	public static final StationRoadInfoVO R130_131 = newVO(Stations.S130, Stations.S131, MIDDLE_TAXI);
	public static final StationRoadInfoVO R130_139 = newVO(Stations.S130, Stations.S139, LEFT_TAXI, RIGHT_METRO);
	
	public static final StationRoadInfoVO R132_140 = newVO(Stations.S132, Stations.S140, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R133_140 = newVO(Stations.S133, Stations.S140, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R133_141 = newVO(Stations.S133, Stations.S141, LEFT_METRO, RIGHT_TAXI);
	public static final StationRoadInfoVO R133_157 = newVO(Stations.S133, Stations.S157, MIDDLE_BUS);
	public static final StationRoadInfoVO R134_141 = newVO(Stations.S134, Stations.S141, MIDDLE_TAXI);
	public static final StationRoadInfoVO R134_142 = newVO(Stations.S134, Stations.S142, MIDDLE_TAXI);
	public static final StationRoadInfoVO R135_136 = newVO(Stations.S135, Stations.S136, MIDDLE_TAXI);
	public static final StationRoadInfoVO R135_143 = newVO(Stations.S135, Stations.S143, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R135_161 = newVO(Stations.S135, Stations.S161, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R136_161 = newVO(Stations.S136, Stations.S161, MIDDLE_BUS);
	public static final StationRoadInfoVO R136_162 = newVO(Stations.S136, Stations.S162, MIDDLE_TAXI);
	public static final StationRoadInfoVO R137_147 = newVO(Stations.S137, Stations.S147, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R138_150 = newVO(Stations.S138, Stations.S150, MIDDLE_TAXI);
	public static final StationRoadInfoVO R138_152 = newVO(Stations.S138, Stations.S152, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R139_140 = newVO(Stations.S139, Stations.S140, MIDDLE_TAXI);
	public static final StationRoadInfoVO R139_153 = newVO(Stations.S139, Stations.S153, LEFT_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R139_154 = newVO(Stations.S139, Stations.S154, MIDDLE_TAXI);
	public static final StationRoadInfoVO R140_154 = newVO(Stations.S140, Stations.S154, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R140_156 = newVO(Stations.S140, Stations.S156, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R141_142 = newVO(Stations.S141, Stations.S142, LEFT_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R141_158 = newVO(Stations.S141, Stations.S158, MIDDLE_TAXI);
	
	public static final StationRoadInfoVO R142_143 = newVO(Stations.S142, Stations.S143, MIDDLE_TAXI);
	public static final StationRoadInfoVO R142_158 = newVO(Stations.S142, Stations.S158, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R143_160 = newVO(Stations.S143, Stations.S160, MIDDLE_TAXI);
	public static final StationRoadInfoVO R144_145 = newVO(Stations.S144, Stations.S145, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R144_163 = newVO(Stations.S144, Stations.S163, MIDDLE_BUS);
	public static final StationRoadInfoVO R144_177 = newVO(Stations.S144, Stations.S177, MIDDLE_TAXI);
	public static final StationRoadInfoVO R145_146 = newVO(Stations.S145, Stations.S146, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R146_147 = newVO(Stations.S146, Stations.S147, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R146_163 = newVO(Stations.S146, Stations.S163, MIDDLE_TAXI);
	public static final StationRoadInfoVO R147_163 = newVO(Stations.S147, Stations.S163, MIDDLE_METRO);
	public static final StationRoadInfoVO R147_164 = newVO(Stations.S147, Stations.S164, MIDDLE_TAXI);
	public static final StationRoadInfoVO R148_149 = newVO(Stations.S148, Stations.S149, MIDDLE_TAXI);
	public static final StationRoadInfoVO R148_164 = newVO(Stations.S148, Stations.S164, MIDDLE_TAXI);
	public static final StationRoadInfoVO R149_150 = newVO(Stations.S149, Stations.S150, MIDDLE_TAXI);
	public static final StationRoadInfoVO R149_165 = newVO(Stations.S149, Stations.S165, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R150_151 = newVO(Stations.S150, Stations.S151, MIDDLE_TAXI);
	
	public static final StationRoadInfoVO R151_152 = newVO(Stations.S151, Stations.S152, MIDDLE_TAXI);
	public static final StationRoadInfoVO R151_166 = newVO(Stations.S151, Stations.S166, MIDDLE_TAXI);
	public static final StationRoadInfoVO R152_153 = newVO(Stations.S152, Stations.S153, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R153_154 = newVO(Stations.S153, Stations.S154, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R153_165 = newVO(Stations.S153, Stations.S165, MIDDLE_METRO);
	public static final StationRoadInfoVO R153_166 = newVO(Stations.S153, Stations.S166, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R153_167 = newVO(Stations.S153, Stations.S167, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R154_155 = newVO(Stations.S154, Stations.S155, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R155_156 = newVO(Stations.S155, Stations.S156, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R155_167 = newVO(Stations.S155, Stations.S167, MIDDLE_TAXI);
	public static final StationRoadInfoVO R155_168 = newVO(Stations.S155, Stations.S168, MIDDLE_TAXI);
	public static final StationRoadInfoVO R156_157 = newVO(Stations.S156, Stations.S157, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R156_169 = newVO(Stations.S156, Stations.S169, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R157_158 = newVO(Stations.S157, Stations.S158, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R157_170 = newVO(Stations.S157, Stations.S170, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R158_159 = newVO(Stations.S158, Stations.S159, MIDDLE_TAXI);
	public static final StationRoadInfoVO R159_170 = newVO(Stations.S159, Stations.S170, MIDDLE_TAXI);
	public static final StationRoadInfoVO R159_172 = newVO(Stations.S159, Stations.S172, MIDDLE_TAXI);
	public static final StationRoadInfoVO R159_186 = newVO(Stations.S159, Stations.S186, MIDDLE_TAXI);
	public static final StationRoadInfoVO R159_198 = newVO(Stations.S159, Stations.S198, MIDDLE_TAXI);
	public static final StationRoadInfoVO R160_161 = newVO(Stations.S160, Stations.S161, MIDDLE_TAXI);
	public static final StationRoadInfoVO R160_173 = newVO(Stations.S160, Stations.S173, MIDDLE_TAXI);
	
	public static final StationRoadInfoVO R161_174 = newVO(Stations.S161, Stations.S174, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R162_175 = newVO(Stations.S162, Stations.S175, MIDDLE_TAXI);
	public static final StationRoadInfoVO R163_164 = newVO(Stations.S163, Stations.S164, MIDDLE_METRO);
	public static final StationRoadInfoVO R163_177 = newVO(Stations.S163, Stations.S177, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R163_178 = newVO(Stations.S163, Stations.S178, MIDDLE_BUS);
	public static final StationRoadInfoVO R164_165 = newVO(Stations.S164, Stations.S165, MIDDLE_METRO);
	public static final StationRoadInfoVO R164_178 = newVO(Stations.S164, Stations.S178, MIDDLE_TAXI);
	public static final StationRoadInfoVO R164_179 = newVO(Stations.S164, Stations.S179, MIDDLE_TAXI);
	public static final StationRoadInfoVO R165_179 = newVO(Stations.S165, Stations.S179, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R165_180 = newVO(Stations.S165, Stations.S180, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R166_181 = newVO(Stations.S166, Stations.S181, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R166_183 = newVO(Stations.S166, Stations.S183, MIDDLE_TAXI);
	public static final StationRoadInfoVO R167_168 = newVO(Stations.S167, Stations.S168, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R167_183 = newVO(Stations.S167, Stations.S183, MIDDLE_TAXI);
	public static final StationRoadInfoVO R168_184 = newVO(Stations.S168, Stations.S184, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R169_184 = newVO(Stations.S169, Stations.S184, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R170_185 = newVO(Stations.S170, Stations.S185, LEFT_BUS, RIGHT_TAXI);
	
	public static final StationRoadInfoVO R171_173 = newVO(Stations.S171, Stations.S173, MIDDLE_TAXI);
	public static final StationRoadInfoVO R171_175 = newVO(Stations.S171, Stations.S175, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R171_199 = newVO(Stations.S171, Stations.S199, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R172_187 = newVO(Stations.S172, Stations.S187, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R173_174 = newVO(Stations.S173, Stations.S174, MIDDLE_TAXI);
	public static final StationRoadInfoVO R173_188 = newVO(Stations.S173, Stations.S188, MIDDLE_TAXI);
	public static final StationRoadInfoVO R174_175 = newVO(Stations.S174, Stations.S175, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R176_177 = newVO(Stations.S176, Stations.S177, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R176_189 = newVO(Stations.S176, Stations.S189, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R178_189 = newVO(Stations.S178, Stations.S189, MIDDLE_TAXI);
	public static final StationRoadInfoVO R178_191 = newVO(Stations.S178, Stations.S191, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R179_191 = newVO(Stations.S179, Stations.S191, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R180_181 = newVO(Stations.S180, Stations.S181, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R180_192 = newVO(Stations.S180, Stations.S192, MIDDLE_BUS);
	public static final StationRoadInfoVO R180_193 = newVO(Stations.S180, Stations.S193, LEFT_BUS, RIGHT_TAXI);
	
	public static final StationRoadInfoVO R181_182 = newVO(Stations.S181, Stations.S182, MIDDLE_TAXI);
	public static final StationRoadInfoVO R181_193 = newVO(Stations.S181, Stations.S193, MIDDLE_TAXI);
	public static final StationRoadInfoVO R182_183 = newVO(Stations.S182, Stations.S183, MIDDLE_TAXI);
	public static final StationRoadInfoVO R182_195 = newVO(Stations.S182, Stations.S195, MIDDLE_TAXI);
	public static final StationRoadInfoVO R183_196 = newVO(Stations.S183, Stations.S196, MIDDLE_TAXI);
	public static final StationRoadInfoVO R184_185 = newVO(Stations.S184, Stations.S185, LEFT_BUS, MIDDLE_TAXI, RIGHT_METRO);
	public static final StationRoadInfoVO R184_196 = newVO(Stations.S184, Stations.S196, LEFT_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R184_197 = newVO(Stations.S184, Stations.S197, MIDDLE_TAXI);
	public static final StationRoadInfoVO R185_186 = newVO(Stations.S185, Stations.S186, MIDDLE_TAXI);
	public static final StationRoadInfoVO R185_198 = newVO(Stations.S185, Stations.S198, LEFT_METRO, RIGHT_BUS);
	public static final StationRoadInfoVO R186_198 = newVO(Stations.S186, Stations.S198, MIDDLE_TAXI);
	public static final StationRoadInfoVO R187_188 = newVO(Stations.S187, Stations.S188, MIDDLE_TAXI);
	public static final StationRoadInfoVO R187_198 = newVO(Stations.S187, Stations.S198, LEFT_METRO, MIDDLE_TAXI, RIGHT_BUS);
	public static final StationRoadInfoVO R188_199 = newVO(Stations.S188, Stations.S199, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R189_190 = newVO(Stations.S189, Stations.S190, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R190_191 = newVO(Stations.S190, Stations.S191, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R190_192 = newVO(Stations.S190, Stations.S192, LEFT_BUS, RIGHT_TAXI);
	
	public static final StationRoadInfoVO R191_192 = newVO(Stations.S191, Stations.S192, MIDDLE_TAXI);
	public static final StationRoadInfoVO R192_194 = newVO(Stations.S192, Stations.S194, MIDDLE_TAXI);
	public static final StationRoadInfoVO R193_194 = newVO(Stations.S193, Stations.S194, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R194_195 = newVO(Stations.S194, Stations.S195, LEFT_BUS, RIGHT_TAXI);
	public static final StationRoadInfoVO R195_196 = newVO(Stations.S195, Stations.S196, MIDDLE_BUS);
	public static final StationRoadInfoVO R195_197 = newVO(Stations.S195, Stations.S197, MIDDLE_TAXI);
	public static final StationRoadInfoVO R196_197 = newVO(Stations.S196, Stations.S197, MIDDLE_TAXI);
	public static final StationRoadInfoVO R198_199 = newVO(Stations.S198, Stations.S199, MIDDLE_TAXI);
}
